name: tda_financial_time_series
channels:
  - conda-forge
dependencies:
  - gudhi>=3.5.0
  - scikit-learn
  - plotly
  - numpy
  - pandas
  - nodejs
  - ipywidgets
  - jupyterlab>=3.1
  - anywidget
  - voila>=0.2.11
